name: Packaging and Publishing

on:
  workflow_run:
    workflows: ['release']
    types:
      - completed

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag from GITHUB_REF_NAME
        id: extract-tag
        run: echo "::set-output name=tag::${GITHUB_REF_NAME}"

      - name: Build Docker image
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/flynow:${{ steps.extract-tag.outputs.tag }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flynow:${{ steps.extract-tag.outputs.tag }}
